version: '2'

services:
  server-udp:
    image: ${DOCKER_REGISTRY}monstrenyatko/openvpn-server
    volumes:
      - udp-config:/etc/openvpn:rw
      - data-pki:/mnt/pki:rw

volumes:
  udp-config:
  data-pki:
